remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Julian Alexis Garcia Herrera
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/xhotto-d02a8.appspot.com/o/Imagen%20de%20WhatsApp%202023-09-24%20a%20las%2017.18.46.jpg?alt=media&token=d3cb0f56-4716-4120-83fb-ab7c0c5700cc

